#ifndef CONFIGURACAO_H
#define CONFIGURACAO_H
/* Personalize aqui e recompile o jogo. */
#define TITULO_JOGO "Cobrinha Neon"
#define LARGURA_TABULEIRO 24
#define ALTURA_TABULEIRO 18
#define COMPRIMENTO_INICIAL 4
#define PONTOS_POR_ALIMENTO 10
#define INTERVALO_INICIAL_MS 150
#define INTERVALO_MINIMO_MS 65
#define ACELERACAO_MS 4
#define QUANTIDADE_OBSTACULOS 12
#define PORTA_SERVIDOR 8000
#define MAXIMO_PARTIDAS 256
#define VALIDADE_PARTIDA_SEGUNDOS 3600
#endif
